server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yebali/spring-cloud-config-sample # git address
          default-label: main # branch name
          search-paths: configs # path
        encrypt:
          enabled: false # encrypt properties
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: '*'

encrypt:
  key: steppay-is-best-payment...maybe
